spring.application.name=cocreate
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=busykiwi
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true